### ISSUE TITLE
bug: primary industries misalign their water input

### ISSUE THREAD

**Issue by bahrmichael** [bahrmichael/factorio-tycoon#184]
Only happens sometimes, and looks like it's less than half a tile off. Maybe we need to round the position we place them at?

**Comment by bahrmichael** [comment]
Haven't seen this again since, maybe because of fixing the rotatability

**Comment by bahrmichael** [comment]
Still an issue, seems to only show up if the screen does not have too high of a resolution. See https://github.com/bahrmichael/factorio-tycoon/pull/216

**Comment by winex** [comment]
https://github.com/winex/factorio-tycoon/commit/1b0931324d61e987af45324c0ada750600117794 looks really good: ![scrot 20240227_180000 collage](https://github.com/bahrmichael/factorio-tycoon/assets/639989/2ac5c763-0dae-4c60-8fa4-13f5d6072ca9)
