### ISSUE TITLE
mod support: integrating with omnifluids

### ISSUE THREAD

**Issue by bahrmichael** [bahrmichael/factorio-tycoon#220]
https://mods.factorio.com/mod/tycoon/discussion/654a8ac27ee4caf970a55db4

> After checking it, you can call 
omni.fluid.add_mining_fluid("water")
 which will force conversion recipes for water no matter of the mods that are installed.

**Comment by bahrmichael** [comment]
Marked this mod as incompatible until I get to fix it: https://github.com/bahrmichael/factorio-tycoon/pull/226

**Comment by winex** [comment]
i've found that this mod is `not found` while looking at https://mods.factorio.com/mod/tycoon/dependencies , so:
- added a change to correct name in #313
