### ISSUE TITLE
bug: v0.4.0 regression - cities doesn't consume construction materials from stores

### ISSUE THREAD

**Issue by winex** [bahrmichael/factorio-tycoon#273]
- `consumeItem()` function is not called anymore starting from `v0.4.0`
```
$ grep -Rn --include="*.lua" -i 'consume' .                                                                   
./control.lua:73:local function consume_resources()
./control.lua:75:        Consumption.consumeBasicNeeds(city)
./control.lua:76:        Consumption.consumeAdditionalNeeds(city)
./control.lua:86:    consume_resources()
./control_old.lua:879:                Consumption.consumeItem(item, hardwareStores, city, true)
./control_old.lua:1081:            Consumption.consumeBasicNeeds(city)
./control_old.lua:1082:            Consumption.consumeAdditionalNeeds(city)
```
this block of `City:: startConstruction()` says:
https://github.com/bahrmichael/factorio-tycoon/blob/743d716ab55fd0c79a4ef0a3f8d9c98c1b5f20cf/city.lua#L836-L842
but it's not known where such "outside" function is supposed to be in the new code :(

**Comment by bahrmichael** [comment]
Thanks for reporting this! I had a feeling something was off.

Fixed this in 0.4.5, see https://github.com/bahrmichael/factorio-tycoon/commit/12c77d99f99412d01a10e3bf3e6c3f4b2d757cc2
