### ISSUE TITLE
bug: used-bottles-store built outside of CITY_RADIUS won't get used bottles

### ISSUE THREAD

**Issue by winex** [bahrmichael/factorio-tycoon#321]
### reqs
1. city is already large enough that it builds houses farther than `Constants.CITY_RADIUS`
2. player researches `bottling`, so city must build `tycoon-used-bottles-store` somewhere outside of that limit

### what happens
if any `tycoon-used-bottles-store` is outside of radius, this code denies to cache it in `global.tycoon_cities[N].special_buildings.other[name]`:
https://github.com/bahrmichael/factorio-tycoon/blob/1bf7bd54538460bfc483e0b6fb7ec6d19491bcc2/util.lua#L288-L297

moving it manually (`PickerDollies` mod) inside city radius makes it working again...

### possible solutions
- **bad**: increase search radius for all special buildings
- good 1/3: such special buildings should never be built outside of city radius. make some space closer to center somehow (shoot some houses?)
- good 2/3: building locations should be iterated in spiral from the center, adding some "bad" weight to queue in case of failure, so that very bad locations will be checked very rarely instead of linear iteration
- good 3/3: increase attempts (`10` currently) and check that this works... ;)

**Comment by bahrmichael** [comment]
Thanks for reporting this!

I want to take a slightly different approach: A different mechanism for finding entities that the city places itself. Just as we store the town hall in a dedicated field, I'll do the same with the bottle return station.

```
        special_buildings = {
            town_hall = nil,
            other = {}
        },
```

Eventually we may want to restructure that to

```
        special_buildings = {
            city_owned = {},
            player_owned = {}
        },
```

I think that way I can just drop the call to list_special_buildings.

Long term I'm thinking about a city radius that expands as the city grows (like a polygon), but that's still a bit further out.
