### ISSUE TITLE
fix: make primary industries more visible

### ISSUE THREAD

**Issue by bahrmichael** [bahrmichael/factorio-tycoon#33]
Need to add (probably english) names on the map to make them more visible.

**Comment by bahrmichael** [comment]
Heads up @LUISDASARTIMANHAS that there will be another place than the regular translation files that some localized text comes from.

I'm not sure how the runtime can figure out what language the player is using, and even less have an idea of how it should behave in multiplayer.

**Comment by LUISDASARTIMANHAS** [comment]
The location file is managed by the game,But it would translate without a problem
