### ISSUE TITLE
Bug construction

### ISSUE THREAD

**Issue by LUISDASARTIMANHAS** [bahrmichael/factorio-tycoon#41]
construction horizontally and occupied space vertically

![image](https://github.com/bahrmichael/factorio-tycoon/assets/75493473/56a20884-653f-4831-b205-63c9581d720e)

**Comment by bahrmichael** [comment]
Thank you! I've seen that during development, and wasn't sure if it shows up in published releases. Will investigate :)

**Comment by bahrmichael** [comment]
Maybe factorio gets confused by the shorthand positions. I'll try specifying them as coordinates and see how it goes.

**Comment by LUISDASARTIMANHAS** [comment]
the conflict and selection coordinates are inverted, I think if you change the x to y it should work
collision_box = { { -8.4, -2.4}, {8.4, 2.4} },
selection_box = { { -8.5, -2.5}, {8.5, 2.5} },
collision_box = { { -x1, -y1}, {x2, y2} },
selection_box = { { -x1, -y1}, {x2, y2} },

left:x1
right:x2
bottom: y1
top: y2

**Comment by bahrmichael** [comment]
This issue is a bit more confusing than just having the wrong numbers.

I've seen this again yesterday in my own test:

<img width="791" alt="Screenshot 2023-10-11 at 11 19 26" src="https://github.com/bahrmichael/factorio-tycoon/assets/1830132/00a7a2f9-0ce1-46d5-a2de-bdce2779cf91">

Today when I reconstruct that building (or construct it in another save):

<img width="887" alt="Screenshot 2023-10-11 at 11 21 00" src="https://github.com/bahrmichael/factorio-tycoon/assets/1830132/7f9263f4-1526-4f5b-92f4-d821e749de2a">

I only made a formatting change, that really can't be the reason:

<img width="633" alt="Screenshot 2023-10-11 at 11 22 38" src="https://github.com/bahrmichael/factorio-tycoon/assets/1830132/fec8bf89-440e-4981-ba49-209987c12a63">

**Comment by bahrmichael** [comment]
I also tried replacing the shorthand version `{x, y}` with the longhand version `{x=x, y=y}`, but the squeak through mod can't handle that.

**Comment by LUISDASARTIMANHAS** [comment]
So the problem is the image since the game is rotating the hitbox and the structure but the image is not rotated, try putting 2 frames in the official image

**Comment by LUISDASARTIMANHAS** [comment]
Just like the game does with the car that has 64 positions and 64 images in just 1

**Comment by LUISDASARTIMANHAS** [comment]
When you use the R button or rotate the game changes the position and takes the image that fits the position, in this case I notice that the butcher's shop only has 1 image

**Comment by LUISDASARTIMANHAS** [comment]
I'm working on this bug but I only see the solution of adding another image or leaving the butcher shop fixed

**Comment by LUISDASARTIMANHAS** [comment]
This is an example of what I use in my constructions
local path_main = "__Applied-Energistics-2__/"

data:extend({
    {
        type = "assembling-machine",
        name = "16k-crafting-storage-entidade",
        icon = path_main .. "graficos/Blocos/16k_crafting_storage.png",
        icon_size = 128,
        icon_mipmaps = 4,
        minable = { mining_time = 1, result = "16k-crafting-storage" },
        max_health = 350,
        crafting_speed = 4,
        ingredient_count = 3,
        off_when_no_fluid_recipe = true,
        energy_usage = "300kW",
        buffer_capacity = "1MW",
        crafting_categories = { "inscriber","crafting" },
        -- corpse = "big-remnants",
        corpse = "assembling-machine-2-remnants",
        -- dying_explosion = "big-explosion",
        dying_explosion = "assembling-machine-2-explosion",
        alert_icon_shift = { -0.09375, -0.375 },
        collision_box = {
            { -1.2, -1.2 },
            { 1.2,  1.2 }
        },
        selection_box = {
            { -1.5, -1.5 },
            { 1.5,  1.5 }
        },
        drawing_box = {
            { -1.5, -1.5 },
            { 1.5,  1.5 }
        },
        energy_source = {
            emissions_per_minute = 3,
            type = "electric",
            usage_priority = "secondary-input"
        },
        resistances = {
            {
                type = "fire",
                percent = 70
            }
        },
        damaged_trigger_effect = {
            entity_name = "spark-explosion",
            type = "create-entity",
            damage_type_filters = "fire",
            offsets = { { 0, 1 } },
            offset_deviation = { { -0.5, -0.5 }, { 0.5, 0.5 } }
        },
        allowed_effects = {
            "consumption",
            "speed",
            "productivity",
            "pollution"
        },
        flags = {
            "placeable-neutral",
            "placeable-player",
            "player-creation"
        },
        placeable_by = {
            item = "16k-crafting-storage",
            count = 1
        },
        module_specification = {
            module_slots = 0,
            module_info_icon_shift = { 0, 0.5 }
        },
        working_sound = {
            sound = {
                { filename = "__base__/sound/assembling-machine-t2-1.ogg", volume = 0.45 }
            },
            fade_in_ticks = 4,
            audible_distance_modifier = 0.5,
            fade_out_ticks = 20
        },
        vehicle_impact_sound = {
            {
                filename = "__base__/sound/car-metal-impact-2.ogg",
                volume = 0.5
            },
            {
                filename = "__base__/sound/car-metal-impact-3.ogg",
                volume = 0.5
            },
            {
                filename = "__base__/sound/car-metal-impact-4.ogg",
                volume = 0.5
            },
            {
                filename = "__base__/sound/car-metal-impact-5.ogg",
                volume = 0.5
            },
            {
                filename = "__base__/sound/car-metal-impact-6.ogg",
                volume = 0.5
            }
        },
        animation = {
            layers = {
                {
                    frame_count = 1,
                    filename = path_main .. "graficos/Blocos/16k_crafting_storage.png",
                    hr_version = {
                        frame_count = 1,
                        filename = path_main .. "graficos/Blocos/16k_crafting_storage.png",
                        height = 128,
                        line_length = 1,
                        shift = { 0, 0.125 },
                        scale = 0.5,
                        priority = "high",
                        width = 128
                    },
                    height = 128,
                    line_length = 1,
                    shift = { 0, 0.125 },
                    priority = "high",
                    width = 128
                }
            }
        },
        close_sound = {
            {
                filename = "__base__/sound/machine-close.ogg",
                volume = 0.5
            }
        },
        open_sound = {
            {
                filename = "__base__/sound/machine-open.ogg",
                volume = 0.5
            }
        },
    }
})

**Comment by LUISDASARTIMANHAS** [comment]
![Frame 1](https://github.com/bahrmichael/factorio-tycoon/assets/75493473/dca7b9a1-a97a-4bf0-a1fd-f91f7a92d213)

I was thinking about that

**Comment by bahrmichael** [comment]
True, if we can't find the root cause we need to add a vertical image.

**Comment by bahrmichael** [comment]
<img width="901" alt="Screenshot 2023-10-12 at 08 45 51" src="https://github.com/bahrmichael/factorio-tycoon/assets/1830132/8261f695-1706-4a73-9108-b4a79a943d1e">

Problem happened again in editor mode.
